added uhubctl -N, added retry

diff --git a/uhub b/uhub
--- a/uhub
+++ b/uhub
@@ -7,9 +7,8 @@ hubs=(8-4)
 #hubs=(2-6 2-5 2-4 2-3 10-4 8-4 6-4 4-4)
 #TODO: Manually specify the number of device (RealSense) per hub
 dev_per_hub=2
-#TODO: Manually specify how many times we retry to check and sleep time
-num_to_check=10
-sleep_time=3
+#TODO: Manually specify how many times to retry power cycle
+retry=3
 
 uhub() {
     local a=${1:?}
@@ -40,30 +39,48 @@ cycle_hub() {
 
 
 cycle() {
-    #lsusb | grep Intel
-
-    local hub
-    for hub in $hubs; do
-        cycle_hub $hub &  # Run in parallel
-    done
-    wait
-
-    for i in {1..$num_to_check}
-    do 
-        if [ $(lsusb | grep -c Intel) -eq $((${#hubs[@]} * $dev_per_hub)) ] 
+    for i in {1..$retry}
+    do
+        local hub
+        for hub in $hubs; do
+            cycle_hub $hub &  # Run in parallel
+        done
+        wait
+    
+        sleep 1
+    
+        uhubctl -N  # This is (sometimes) required to find the hub/port again.
+    
+        local found_all
+        [ $(lsusb | grep -c Intel) -eq $((${#hubs[@]} * $dev_per_hub)) ]
+        found_all=$?
+    
+        if [ $found_all -eq 1 ]
         then
-            echo "Found all devices"
-            break
+            exit 0
         else
-            if [ $i -eq $num_to_check ]
-            then
-                echo "Error: Couldn't find all devices for $(($num_to_check * $sleep_time))"
-                exit 1
-            fi
-            echo "Couldn't find all devices. Sleep $sleep_time seconds"
-            sleep $sleep_time
+            echo "Couldn't find all devices"
         fi
     done
+    echo "Failed"
+    exit 1
+
+#    for i in {1..$num_to_check}
+#    do 
+#        if [ $(lsusb | grep -c Intel) -eq $((${#hubs[@]} * $dev_per_hub)) ] 
+#        then
+#            echo "Found all devices"
+#            break
+#        else
+#            if [ $i -eq $num_to_check ]
+#            then
+#                echo "Error: Couldn't find all devices for $(($num_to_check * $sleep_time))"
+#                exit 1
+#            fi
+#            echo "Couldn't find all devices. Sleep $sleep_time seconds"
+#            sleep $sleep_time
+#        fi
+#    done
 }
 
 "$1" "${@:2}"
